# Generated by Django 3.0.8 on 2020-08-02 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatList',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('name_eng', models.CharField(default='stat name', max_length=30)),
                ('skill_base', models.BooleanField(default=False)),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SecStatList',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='bonus1',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='bonus1_num',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='bonus2',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='bonus2_num',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='bonus3',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='bonus3_num',
        ),
        migrations.RemoveField(
            model_name='racelist',
            name='other_bonus',
        ),
        migrations.AlterField(
            model_name='racelist',
            name='info',
            field=models.CharField(default='Тут информация о <django.db.models.fields.CharField>, описание фишек и тп', max_length=600),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.StatList'),
        ),
        migrations.AlterField(
            model_name='skilllist',
            name='depended_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.StatList'),
        ),
        migrations.DeleteModel(
            name='MainStatList',
        ),
    ]
