# Generated by Django 3.0.8 on 2020-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_skilllist_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstat',
            name='skill_base',
            field=models.BooleanField(default=False),
        ),
    ]
