# Generated by Django 3.0.8 on 2020-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_characterstat_skill_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllist',
            name='value',
        ),
        migrations.AddField(
            model_name='skilllist',
            name='short_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0481FB38>', max_length=10),
        ),
    ]
