# Generated by Django 3.0.8 on 2020-08-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20200806_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllist',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='statlist',
            name='value',
        ),
        migrations.AddField(
            model_name='statlist',
            name='short_name',
            field=models.CharField(default='NAME', max_length=10),
        ),
    ]
