# Generated by Django 3.0.8 on 2020-09-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_characterracetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterracetest',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.Character'),
        ),
        migrations.AlterField(
            model_name='characterracetest',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.RaceList'),
        ),
    ]
