# Generated by Django 3.0.8 on 2020-09-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_auto_20200928_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterracetest',
            name='id',
        ),
        migrations.AlterField(
            model_name='characterracetest',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='constructor.Character'),
        ),
    ]
