# Generated by Django 3.0.8 on 2020-09-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_auto_20200928_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterprof',
            name='id',
        ),
        migrations.RemoveField(
            model_name='characterprof',
            name='name',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='id',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='name',
        ),
        migrations.AddField(
            model_name='characterprof',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.ProfessionList'),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.RaceList'),
        ),
        migrations.AlterField(
            model_name='characterprof',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='constructor.Character'),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='constructor.Character'),
        ),
        migrations.DeleteModel(
            name='CharacterRaceTest',
        ),
    ]
