# Generated by Django 3.0.8 on 2020-09-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_auto_20200928_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterrace',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='race',
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(blank=True, default='Маг', null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.ProfessionList'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.RaceList'),
        ),
        migrations.DeleteModel(
            name='CharacterProf',
        ),
        migrations.DeleteModel(
            name='CharacterRace',
        ),
    ]
