# Generated by Django 3.0.8 on 2020-09-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0016_auto_20200928_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(default='Маг', null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.ProfessionList'),
        ),
    ]
